namespace P5R.CostumeFramework.Models;

internal enum CostumeSet
{
    Default,
    Summer_Uniform,
    Winter_Uniform,
    Summer_Clothes,
    Winter_Clothes,
    Tracksuit,
    Swimsuit,
    Loungewear,
    Gekkoukan_High,
    Yasogami_High,
    St_Hermelin_High,
    Seven_Sisters_High,
    Catherine,
    Karukozaka_High,
    Butler_Suit,
    Christmas_Outfit,
    Dancewear,
    Shadow_Ops_Uniform,
    Samurai_Garb,
    Yumizuki_High,
    Starlight_Outfit,
    Moonlight_Outfit,
    Ultramarine_Outfit,
    Featherman_Suit,
    Demonica_Head,
    Demonica_Suit,
    New_Cinema_Outfit,
}
